apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: samarth502/task9p:v2
        ports:
        - containerPort: 3003
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
