version: '3.8'

services:
  web:
    build: .
    ports:
      - "3003:3003"
    restart: always
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003"]
      interval: 30s
      timeout: 10s
      retries: 3
